extends Node2D
## Overworld map painter + battle controller.
## Paints a test map programmatically each run using the FR/LG-ripped tileset
## at assets/tilesets/frlg/frlg_outdoor.tres. The atlas is generated by
## tools/build_frlg_atlas.py — see that file for the tile layout.

const MAP_W := 20
const MAP_H := 34                # extended south for path-type demo rings
const SOURCE_ID := 0              # single TileSetAtlasSource in the TileSet

# ---- Atlas coords (must match tools/build_frlg_atlas.py) -----------------

# Grass pool: random 6-variant selection for plain grass cells.
const GRASS_POOL: Array[Vector2i] = [
	Vector2i(0, 0), Vector2i(1, 0), Vector2i(2, 0),
	Vector2i(3, 0), Vector2i(4, 0), Vector2i(5, 0),
]
const TALL_GRASS   := Vector2i(6, 0)    # tall_grass=true (encounter tile)
const FLOWER       := Vector2i(7, 0)
const BUSH_SINGLE  := Vector2i(8, 0)    # solid
const SMALL_TREE   := Vector2i(9, 0)    # solid
# Bush-hedge 3-tile horizontal strip (solid).
const BUSH_EDGE_L  := Vector2i(0, 2)
const BUSH_EDGE_M  := Vector2i(1, 2)
const BUSH_EDGE_R  := Vector2i(2, 2)

# Path groups — 13 named tiles per group forming a 5x3 autotile block.
# Each dict key maps to the atlas coord for that tile role. Keys:
#   middle         — all-path, no grass on any side
#   left/right/top/bottom_edge — grass on that side, path elsewhere
#   tl/tr/bl/br_corner — OUTER corners (grass in that corner of tile)
#   int_se/sw/ne/nw — INTERIOR corners (grass jutting INTO path from that corner)
const DIRT_PATH := {
	"middle":       Vector2i(0, 4), "left_edge":   Vector2i(1, 4),
	"right_edge":   Vector2i(2, 4), "top_edge":    Vector2i(3, 4),
	"bottom_edge":  Vector2i(4, 4), "bl_corner":   Vector2i(1, 5),
	"br_corner":    Vector2i(2, 5), "tl_corner":   Vector2i(3, 5),
	"tr_corner":    Vector2i(4, 5), "int_se":      Vector2i(1, 6),
	"int_sw":       Vector2i(2, 6), "int_ne":      Vector2i(3, 6),
	"int_nw":       Vector2i(4, 6),
}
const FAINT_GRASS_PATH := {
	"middle":       Vector2i(5, 4), "left_edge":   Vector2i(6, 4),
	"right_edge":   Vector2i(7, 4), "top_edge":    Vector2i(8, 4),
	"bottom_edge":  Vector2i(9, 4), "bl_corner":   Vector2i(6, 5),
	"br_corner":    Vector2i(7, 5), "tl_corner":   Vector2i(8, 5),
	"tr_corner":    Vector2i(9, 5), "int_se":      Vector2i(6, 6),
	"int_sw":       Vector2i(7, 6), "int_ne":      Vector2i(8, 6),
	"int_nw":       Vector2i(9, 6),
}
const ROCKY_DIRT_PATH := {
	"middle":       Vector2i(0, 7), "left_edge":   Vector2i(1, 7),
	"right_edge":   Vector2i(2, 7), "top_edge":    Vector2i(3, 7),
	"bottom_edge":  Vector2i(4, 7), "bl_corner":   Vector2i(1, 8),
	"br_corner":    Vector2i(2, 8), "tl_corner":   Vector2i(3, 8),
	"tr_corner":    Vector2i(4, 8), "int_se":      Vector2i(1, 9),
	"int_sw":       Vector2i(2, 9), "int_ne":      Vector2i(3, 9),
	"int_nw":       Vector2i(4, 9),
}
const CAVE_PATH := {
	"middle":       Vector2i(5, 7), "left_edge":   Vector2i(6, 7),
	"right_edge":   Vector2i(7, 7), "top_edge":    Vector2i(8, 7),
	"bottom_edge":  Vector2i(9, 7), "bl_corner":   Vector2i(6, 8),
	"br_corner":    Vector2i(7, 8), "tl_corner":   Vector2i(8, 8),
	"tr_corner":    Vector2i(9, 8), "int_se":      Vector2i(6, 9),
	"int_sw":       Vector2i(7, 9), "int_ne":      Vector2i(8, 9),
	"int_nw":       Vector2i(9, 9),
}
const CEMENT_PATH := {
	"middle":       Vector2i(0, 10), "left_edge":  Vector2i(1, 10),
	"right_edge":   Vector2i(2, 10), "top_edge":   Vector2i(3, 10),
	"bottom_edge":  Vector2i(4, 10), "bl_corner":  Vector2i(1, 11),
	"br_corner":    Vector2i(2, 11), "tl_corner":  Vector2i(3, 11),
	"tr_corner":    Vector2i(4, 11), "int_se":     Vector2i(1, 12),
	"int_sw":       Vector2i(2, 12), "int_ne":     Vector2i(3, 12),
	"int_nw":       Vector2i(4, 12),
}
const STONE_PATH := {
	"middle":       Vector2i(5, 10), "left_edge":  Vector2i(6, 10),
	"right_edge":   Vector2i(7, 10), "top_edge":   Vector2i(8, 10),
	"bottom_edge":  Vector2i(9, 10), "bl_corner":  Vector2i(6, 11),
	"br_corner":    Vector2i(7, 11), "tl_corner":  Vector2i(8, 11),
	"tr_corner":    Vector2i(9, 11), "int_se":     Vector2i(6, 12),
	"int_sw":       Vector2i(7, 12), "int_ne":     Vector2i(8, 12),
	"int_nw":       Vector2i(9, 12),
}
const ASPHALT_PATH := {
	"middle":       Vector2i(0, 13), "left_edge":  Vector2i(1, 13),
	"right_edge":   Vector2i(2, 13), "top_edge":   Vector2i(3, 13),
	"bottom_edge":  Vector2i(4, 13), "bl_corner":  Vector2i(1, 14),
	"br_corner":    Vector2i(2, 14), "tl_corner":  Vector2i(3, 14),
	"tr_corner":    Vector2i(4, 14), "int_se":     Vector2i(1, 15),
	"int_sw":       Vector2i(2, 15), "int_ne":     Vector2i(3, 15),
	"int_nw":       Vector2i(4, 15),
}

# ---- Map layout ----------------------------------------------------------

# Main 3-wide dirt path across the top half (the original route).
const MAIN_PATH_Y_TOP   := 6
const MAIN_PATH_Y_BOT   := 8
const MAIN_PATH_X_LEFT  := 1
const MAIN_PATH_X_RIGHT := MAP_W - 2

# Encounter (tall-grass) patch — still in the top half.
const ENCOUNTER_RECT := Rect2i(12, 2, 5, 4)  # x=12..16, y=2..5

# Seven 5x5 path rings in the southern half of the map, each wrapping a 1x1
# grass hole in the center. 2-tile-thick perimeter using the full 13-tile
# autotile (edges, outer corners, interior corners).
# Entries: (path_group_dict, top_left_cell_x, top_left_cell_y)
const RING_PLACEMENTS := [
	[&"dirt",        1, 16],
	[&"faint_grass", 7, 16],
	[&"rocky_dirt", 13, 16],
	[&"cave",        1, 23],
	[&"cement",      7, 23],
	[&"stone",      13, 23],
	[&"asphalt",     1, 29],
]

# ---- Node refs ------------------------------------------------------------

@onready var ground: TileMapLayer = $Ground
@onready var objects: TileMapLayer = $Objects
@onready var overhead: TileMapLayer = $Overhead
@onready var player: Node2D = $Player
@onready var encounter_zone: EncounterZone = $EncounterZone
@onready var trainers_root: Node = $Trainers

const BATTLE_SCENE := preload("res://scenes/battle/Battle.tscn")
const TYPE_CHART := preload("res://data/type_chart.tres")
const PARTY_SCREEN := preload("res://scenes/ui/PartyScreen.tscn")
const PartyScreenScript := preload("res://scripts/ui/party_screen.gd")

var _party_screen: PartyScreenScript = null

var _current_battle: Node = null
var _spot_in_progress: bool = false

# ---- Lifecycle ------------------------------------------------------------

func _ready() -> void:
	_paint_ground()
	_paint_objects()
	encounter_zone.wild_encounter_triggered.connect(_on_wild_encounter)
	player.moved.connect(_on_player_moved_trainer_check)
	$Player.party_screen_requested.connect(_on_party_screen_requested)

func _unhandled_input(event: InputEvent) -> void:
	# Debug heal key (Phase 2b). Remove when Pokémon Center lands.
	if event is InputEventKey and event.pressed and not event.echo:
		if event.keycode == KEY_H:
			_debug_heal_party()

func _debug_heal_party() -> void:
	for mon in GameState.player_party:
		mon.current_hp = mon.max_hp()
		mon.status = Enums.StatusCondition.NONE
		for slot in mon.moves:
			slot.pp_current = slot.move.pp
	print("[DEBUG] Party healed.")

# ---- Ground layer --------------------------------------------------------

func _paint_ground() -> void:
	var rng := RandomNumberGenerator.new()
	rng.seed = 1337  # deterministic so the map renders the same every load

	# Everything starts as random plain grass.
	for y in MAP_H:
		for x in MAP_W:
			var g: Vector2i = GRASS_POOL[rng.randi_range(0, GRASS_POOL.size() - 1)]
			ground.set_cell(Vector2i(x, y), SOURCE_ID, g)

	# Encounter (tall-grass) patch.
	for y in range(ENCOUNTER_RECT.position.y, ENCOUNTER_RECT.end.y):
		for x in range(ENCOUNTER_RECT.position.x, ENCOUNTER_RECT.end.x):
			ground.set_cell(Vector2i(x, y), SOURCE_ID, TALL_GRASS)

	# Main 3-tile-thick dirt path through the top half.
	_paint_path_rect(DIRT_PATH,
		MAIN_PATH_X_LEFT, MAIN_PATH_Y_TOP,
		MAIN_PATH_X_RIGHT - MAIN_PATH_X_LEFT + 1, 3)

	# Seven 5x5 path-type demo rings in the southern half.
	for placement in RING_PLACEMENTS:
		var name_k: StringName = placement[0]
		var x0: int = placement[1]
		var y0: int = placement[2]
		_paint_path_ring(_group_by_name(name_k), x0, y0)

	# Decorative flowers (outside any tall-grass/ring so no data is clobbered).
	ground.set_cell(Vector2i(6, 4),  SOURCE_ID, FLOWER)
	ground.set_cell(Vector2i(10, 10), SOURCE_ID, FLOWER)

## Dispatcher for the `const` path-group dictionaries (Godot can't hold them
## in a Dictionary literal because consts can't reference each other cleanly).
func _group_by_name(n: StringName) -> Dictionary:
	match n:
		&"dirt":        return DIRT_PATH
		&"faint_grass": return FAINT_GRASS_PATH
		&"rocky_dirt":  return ROCKY_DIRT_PATH
		&"cave":        return CAVE_PATH
		&"cement":      return CEMENT_PATH
		&"stone":       return STONE_PATH
		&"asphalt":     return ASPHALT_PATH
	return DIRT_PATH

## Paint a solid-fill rectangular path using the 13-tile autotile.
## `w` and `h` are tile counts (minimum 3 in each dimension to exercise the
## corners and edges properly).
func _paint_path_rect(group: Dictionary, x0: int, y0: int, w: int, h: int) -> void:
	var x1 := x0 + w - 1
	var y1 := y0 + h - 1
	for y in range(y0, y1 + 1):
		for x in range(x0, x1 + 1):
			var tile: Vector2i = group["middle"]
			var is_left := x == x0
			var is_right := x == x1
			var is_top := y == y0
			var is_bottom := y == y1
			if is_top and is_left:         tile = group["tl_corner"]
			elif is_top and is_right:      tile = group["tr_corner"]
			elif is_bottom and is_left:    tile = group["bl_corner"]
			elif is_bottom and is_right:   tile = group["br_corner"]
			elif is_top:                   tile = group["top_edge"]
			elif is_bottom:                tile = group["bottom_edge"]
			elif is_left:                  tile = group["left_edge"]
			elif is_right:                 tile = group["right_edge"]
			ground.set_cell(Vector2i(x, y), SOURCE_ID, tile)

## Paint a 5x5 path ring with a 1x1 grass hole at its center (x0+2, y0+2).
## Uses the full 13-tile autotile including interior corners.
func _paint_path_ring(group: Dictionary, x0: int, y0: int) -> void:
	# Outer corners.
	ground.set_cell(Vector2i(x0,     y0),     SOURCE_ID, group["tl_corner"])
	ground.set_cell(Vector2i(x0 + 4, y0),     SOURCE_ID, group["tr_corner"])
	ground.set_cell(Vector2i(x0,     y0 + 4), SOURCE_ID, group["bl_corner"])
	ground.set_cell(Vector2i(x0 + 4, y0 + 4), SOURCE_ID, group["br_corner"])
	# Top and bottom edges (3 tiles each, NOT including corners).
	for dx in [1, 2, 3]:
		ground.set_cell(Vector2i(x0 + dx, y0),     SOURCE_ID, group["top_edge"])
		ground.set_cell(Vector2i(x0 + dx, y0 + 4), SOURCE_ID, group["bottom_edge"])
	# Left and right edges (3 tiles each).
	for dy in [1, 2, 3]:
		ground.set_cell(Vector2i(x0,     y0 + dy), SOURCE_ID, group["left_edge"])
		ground.set_cell(Vector2i(x0 + 4, y0 + dy), SOURCE_ID, group["right_edge"])
	# Interior corners — diagonal-from-the-hole tiles.
	ground.set_cell(Vector2i(x0 + 1, y0 + 1), SOURCE_ID, group["int_se"])  # grass diag SE
	ground.set_cell(Vector2i(x0 + 3, y0 + 1), SOURCE_ID, group["int_sw"])  # grass diag SW
	ground.set_cell(Vector2i(x0 + 1, y0 + 3), SOURCE_ID, group["int_ne"])  # grass diag NE
	ground.set_cell(Vector2i(x0 + 3, y0 + 3), SOURCE_ID, group["int_nw"])  # grass diag NW
	# Edges adjacent to the 1-tile hole at (x0+2, y0+2).
	ground.set_cell(Vector2i(x0 + 2, y0 + 1), SOURCE_ID, group["bottom_edge"])  # grass below
	ground.set_cell(Vector2i(x0 + 1, y0 + 2), SOURCE_ID, group["right_edge"])   # grass right
	ground.set_cell(Vector2i(x0 + 3, y0 + 2), SOURCE_ID, group["left_edge"])    # grass left
	ground.set_cell(Vector2i(x0 + 2, y0 + 3), SOURCE_ID, group["top_edge"])     # grass above
	# Center stays as whatever _paint_ground laid down (plain grass).

# ---- Objects layer (hedges + scattered bushes) ---------------------------

func _paint_objects() -> void:
	# Horizontal top/bottom borders use the 3-tile bush-edge set
	# (L + M*n + R). Vertical sides fall back to single-tile bushes.
	for x in MAP_W:
		var top_tile: Vector2i
		var bot_tile: Vector2i
		if x == 0:
			top_tile = BUSH_EDGE_L; bot_tile = BUSH_EDGE_L
		elif x == MAP_W - 1:
			top_tile = BUSH_EDGE_R; bot_tile = BUSH_EDGE_R
		else:
			top_tile = BUSH_EDGE_M; bot_tile = BUSH_EDGE_M
		objects.set_cell(Vector2i(x, 0),          SOURCE_ID, top_tile)
		objects.set_cell(Vector2i(x, MAP_H - 1),  SOURCE_ID, bot_tile)
	for y in range(1, MAP_H - 1):
		objects.set_cell(Vector2i(0, y),          SOURCE_ID, BUSH_SINGLE)
		objects.set_cell(Vector2i(MAP_W - 1, y),  SOURCE_ID, BUSH_SINGLE)

	# Decorative bushes in the top half (unchanged spots — all in open grass).
	for b in [
		Vector2i(4, 3), Vector2i(8, 11), Vector2i(17, 11),
		Vector2i(3, 10), Vector2i(11, 12),
	]:
		objects.set_cell(b, SOURCE_ID, BUSH_SINGLE)

# ---- Wild encounters + trainer sightline (unchanged) ---------------------

func _on_wild_encounter(species: Species, level: int) -> void:
	if _current_battle != null:
		return
	var wild_moves: Array[Move] = DefaultMovesets.for_species(species.dex_number)
	var wild_mon := PokemonInstance.create(species, level, wild_moves)
	player.input_locked = true
	_current_battle = BATTLE_SCENE.instantiate()
	add_child(_current_battle)
	_current_battle.battle_ended.connect(_on_battle_ended)
	var ctx := BattleContext.with_chart(TYPE_CHART)
	_current_battle.start(GameState.player_party, [wild_mon], ctx)

func _on_battle_ended(_result: BattleResult) -> void:
	if _current_battle:
		_current_battle.queue_free()
		_current_battle = null
	player.input_locked = false

func _on_player_moved_trainer_check(player_cell: Vector2i) -> void:
	if _current_battle != null or _spot_in_progress:
		return
	for t in trainers_root.get_children():
		if not t.has_method("sees_player"):
			continue
		if t.sees_player(player_cell):
			_spot_trainer(t)
			return

func _spot_trainer(trainer: Node) -> void:
	_spot_in_progress = true
	player.input_locked = true
	await trainer.play_alert()
	_start_trainer_battle(trainer)
	_spot_in_progress = false

func _start_trainer_battle(trainer: Node) -> void:
	if _current_battle != null:
		return
	var opponent: PokemonInstance = trainer.build_opponent()
	_current_battle = BATTLE_SCENE.instantiate()
	add_child(_current_battle)
	_current_battle.battle_ended.connect(func(result): _on_trainer_battle_ended(result, trainer))
	var ctx := BattleContext.with_chart(TYPE_CHART)
	ctx.is_trainer = true
	_current_battle.start(GameState.player_party, [opponent], ctx)

func _on_trainer_battle_ended(result: BattleResult, trainer: Node) -> void:
	if result.outcome == BattleResult.Outcome.WIN:
		trainer.mark_defeated()
	_on_battle_ended(result)

func _on_party_screen_requested() -> void:
	if _party_screen != null:
		return
	_party_screen = PARTY_SCREEN.instantiate()
	add_child(_party_screen)
	_party_screen.swap_requested.connect(_on_party_swap)
	_party_screen.cancelled.connect(_on_party_closed)
	$Player.input_locked = true
	_party_screen.open(GameState.player_party, 0, PartyScreenScript.Mode.OVERWORLD_REORDER)

func _on_party_swap(a: int, b: int) -> void:
	var tmp = GameState.player_party[a]
	GameState.player_party[a] = GameState.player_party[b]
	GameState.player_party[b] = tmp

func _on_party_closed() -> void:
	if _party_screen == null:
		return
	_party_screen.queue_free()
	_party_screen = null
	$Player.input_locked = false
